### ISSUE TITLE
By default, do not show on the locked screen

### ISSUE THREAD

**Issue by Wjxfi** [Yanndroid/NotiNotes#14]
I don't think anyone would choose to put this manually. It's not safe.

In much smaller cases, it is useful to put visibility on the locked screen. For example if there is no time to unlock. But not for most people

**Comment by Yanndroid** [comment]
I planned to set the default to what you've chosen on the last note. So if you check "Hide on lockscreen" the first note it will be checked for all the following notes by default.

**Comment by Yanndroid** [comment]
Added to v1.7.0
