### ISSUE TITLE
colored notifications 

### ISSUE THREAD

**Issue by KiraiEEE** [Yanndroid/NotiNotes#27]
Hello,

First of all, thank you for the fantastic app! It has transformed my workflow. 

I have a concern: previously, notifications were colored by the chosen color, but now only the app icon has the color. Could you please bring back that feature? It was perfect.

Thank you!

**Comment by Yanndroid** [comment]
Did you recently update your system? Because on newer Android versions, it is no longer possible to modify the notification view, so no more custom background colors either.
I also miss this feature, but unfortunately there's nothing I can do.

**Comment by KiraiEEE** [comment]
oh!! i dont remember , i will try install older versions and test

**Comment by KiraiEEE** [comment]
i just tested [v1.3.5](https://github.com/Yanndroid/NotiNotes/releases/tag/v1.3.5) and same issue somge
