### ISSUE TITLE
Given Playstore link is not working

### ISSUE THREAD

**Issue by NR8124** [Yanndroid/NotiNotes#3]
![image](https://user-images.githubusercontent.com/88180887/174476719-304f2e45-ab7e-4b8a-bf89-8fb4dc2c9518.png)

**Comment by Yanndroid** [comment]
Yeah I know thanks. I uploaded it on Jun 15 but it takes some time for google to review the app and it should be available soon. I can let you know when it's published.
![image](https://user-images.githubusercontent.com/57589186/174477832-7332b448-a111-44b6-9b30-332fab73bf2f.png)

**Comment by NR8124** [comment]
what else have you planned for future updates ?

**Comment by NR8124** [comment]
The app link is live and working now.. so i m closing this issue.. but there is one more to do.. please consider that one too while next commit
