### ISSUE TITLE
Can U Please Remove the delete confirmation dialogue

### ISSUE THREAD

**Issue by NR8124** [Yanndroid/NotiNotes#4]
Its just annoying when we already have lots of notes in notification and then we want to clear the clutter.
each time it takes the confirmation ...

**Comment by Yanndroid** [comment]
If you uncheck the "lock in notifications" you can simply swipe them away and they'll get removed directly.

**Comment by NR8124** [comment]
no but these can also leads to swipe all the notifications unknowingly.. 
removing the delete dialogue will help us to remove each note manually with being annoyed..

"lock in notification"  is very useful for me
just want that delete dialogue to be removed

**Comment by Yanndroid** [comment]
Ok, I'll think about it 👌

**Comment by NR8124** [comment]
Also can you reduce the app size a little bit.. ?

**Comment by Yanndroid** [comment]
The size is already pretty small: 1.95mb in github releases and 1.77mb on play store. It's literally nothing compared to other apps. And it probably will get a bit more with the next update.

**Comment by NR8124** [comment]
No actually when i installed and started using it then its size is 6.8mb or approx 7mb

**Comment by NR8124** [comment]
> Ok, I'll think about it 👌

Can u please make that work ? removing the delete dialogue..
everything else is just perfect

**Comment by Yanndroid** [comment]
I've been really busy lately, because of school and a lot of other projects and since the next update will be pretty big, it'll take some time. But be assured, I will remove the delete dialog.

**Comment by NR8124** [comment]
Also can u add a option where , whenever we click on any share button.. along with others we get the notinotes option too.. which further leads to keep that shared link to notification bar directly ??

**Comment by Yanndroid** [comment]
delete confirmation removed in v1.3.3


> Also can u add a option where , whenever we click on any share button.. along with others we get the notinotes option too.. which further leads to keep that shared link to notification bar directly ??

Won't implement since you can simply copy and paste.
