### ISSUE TITLE
Recently used color section not working 

### ISSUE THREAD

**Issue by NeeRaj-2401** [Yanndroid/NotiNotes#9]
Expected : there should be list of previously used colors below Recently used color section

But its not working rn the list is empty

**Comment by Yanndroid** [comment]
Yeah I know, haven't implemented this feature yet. Thanks.

**Comment by NR8124** [comment]
@Yanndroid  can u just provide some material color suggestions by default to user ...

**Comment by Yanndroid** [comment]
Fixed in v1.7.0
